### ISSUE TITLE
save model

### ISSUE THREAD

**Issue by AkshatRepo** [gsurma/style_transfer#1]
How do i save that model, I don't want to train it every time with different input image and same style image

**Comment by anubhav1392** [comment]
For keras->just use <model_name>.save('<path>.h2') 
To load model->from keras.models import load_model
model = load_model('<path>')

**Comment by anubhav1392** [comment]
> How do i save that model, I don't want to train it every time with different input image and same style image

For keras->just use <model_name>.save('.h2')
To load model->from keras.models import load_model
model = load_model('')

**Comment by AkshatRepo** [comment]
Yaa..but in style_transfer.ipynb what should i save
